repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -w -i 2 -ci
        language: system
        types: [shell]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck -e SC1091
        language: system
        types: [shell]

      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        files: ^\.github/workflows/.*\.ya?ml$

      - id: yamllint
        name: yamllint
        entry: yamllint -c .yamllint
        language: system
        files: ^.*\.ya?ml$

      - id: yamlfmt
        name: yamlfmt
        entry: yamlfmt -w
        language: system
        files: ^.*\.ya?ml$