repos:
  - repo: local
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

      - id: shfmt
        name: shfmt
        entry: shfmt -w -i 2 -ci
        language: system
        types: [shell]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck -e SC1091
        language: system
        types: [shell]

      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        files: ^\.github/workflows/.*\.ya?ml$

      - id: yamllint
        name: yamllint
        entry: yamllint -c .yamllint
        language: system
        files: ^.*\.ya?ml$

      - id: eslint
        name: eslint
        entry: npx eslint --fix

      - id: prettier
        name: prettier
        entry: npx prettier --write