target-version = "py312"
line-length = 120
preview = true
extend-exclude = [
    ".venv",
]

[lint]
select = [
    "ANN",
    "E",
    "F",
    "I",
    "TCH",
    "UP",
]

[lint.per-file-ignores]
"typings/__builtins__.pyi" = ["F403", "F405"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true