name: ua-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pr: none

variables:
  - group: databricks-ua

extends:
  template: .azuredevops/templates/deploy-databricks-bundle.yml
  parameters:
    targetName: ua
    environmentName: databricks-ua
