name: Deactivate secondary prod environment

on:
  workflow_dispatch:

concurrency:
  group: 'deactivate-secondary-prod-env'
  cancel-in-progress: false

env:
  AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PAT }}
  AZDO_ORG_URL: ${{ secrets.AZDO_ORG_URL }}
  AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
  AZDO_GITHUB_SERVICE_CONNECTION: ${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION }}
  TARGET_ENV: PROD

permissions:
  contents: read

jobs:
  deactivate-secondary-prod-env:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure DevOps extension
        run: bash .github/workflows/scripts/azure/install-azure-devops-extension.sh

      - name: Run Azure DevOps pipeline check that both prod environments are healthy and ready for blue-green swap
        run: bash .github/workflows/scripts/azure/prod-environments-health-check.sh

      - name: Run Azure DevOps pipeline to stop the secondary prod environment
        run: bash .github/workflows/scripts/azure/deactivate-secondary-prod-env.sh
