name: Merge to staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read

jobs:
  ensure-pipeline-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get tags and hash
        id: get-tags
        run: bash .github/workflows/scripts/common/get-tags.sh

      - name: Validate tags
        run: bash .github/workflows/scripts/common/validate-tags.sh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure DevOps extension
        run: bash .github/workflows/scripts/azure/install-azure-devops-extension.sh

      - name: Ensure Azure DevOps pipeline exists
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PAT }}
          AZDO_ORG_URL: ${{ secrets.AZDO_ORG_URL }}
          AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
          AZDO_GITHUB_SERVICE_CONNECTION: ${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION }}
          PIPELINE_NAME: cs-databricks-staging-sync
          PIPELINE_YAML_PATH: .azuredevops/pipelines/cs-databricks-staging-sync.yml
        run: bash echo TODO Implement ensure-azdo-pipeline.sh for staging

      - name: Run Azure DevOps pipeline
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PAT }}
          AZDO_ORG_URL: ${{ secrets.AZDO_ORG_URL }}
          AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
        run: bash echo TODO Implement run-azdo-pipeline.sh for staging