name: Push to main
env:
    AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PAT }}
    AZDO_ORG_URL: ${{ secrets.AZDO_ORG_URL }}
    AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
    AZDO_GITHUB_SERVICE_CONNECTION: ${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION }}
    creds: ${{ secrets.AZURE_CREDENTIALS }}
    TARGET_ENV: DEV

on:
  push:
    branches:
      - main

concurrency:
  group: "push-to-main"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  push-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get target and seed branch names
        id: get-branch-names
        run: bash .github/workflows/scripts/common/get-branch-names.sh

      - name: Check if seed branch name is valid
        id: check-seed-branch
        run: bash .github/workflows/scripts/common/check-seed-branch.sh

      - name: Create a tag from the branch name
        id: create-tag-from-branch-name
        run: bash .github/workflows/scripts/common/create-tag-from-branch-name.sh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure DevOps extension
        run: bash .github/workflows/scripts/azure/install-azure-devops-extension.sh

      - name: Run Azure DevOps pipeline to update Databricks workspace with changes from main
        run: bash .github/workflows/scripts/azure/run-azdo-pipeline.sh
        env:
          PIPELINE_NAME: cs-databricks-update-workspace.yml

      - name: Run Azure DevOps pipeline to execute tests on main
        run: bash .github/workflows/scripts/azure/run-azdo-pipeline.sh
        env:
          PIPELINE_NAME: cs-databricks-run-tests.yml
      