name: 'Push to prod'

on:
  pull_request:
    branches:
      - prod
    types:
      - closed

concurrency:
  group: 'push-to-prod'
  cancel-in-progress: false

env:
  AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PAT }}
  AZDO_ORG_URL: ${{ secrets.AZDO_ORG_URL }}
  AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
  AZDO_GITHUB_SERVICE_CONNECTION: ${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION }}
  BRANCH_NAME: ${{ github.head_ref }}
  TARGET_ENV: PROD

permissions:
  contents: write

jobs:
  push-to-prod:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Local environment setup (for GitHub Job VM)
        run: bash .github/workflows/scripts/common/local-env-setup.sh

      - name: Check if source branch name is valid for prod
        run: python .github/workflows/scripts/common/check-branch-name.py

      - name: Create a tag from the source branch name
        id: create-tag-from-branch-name
        run: python .github/workflows/scripts/common/create-tag-from-branch-name.py

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure DevOps extension
        run: bash .github/workflows/scripts/azure/install-azure-devops-extension.sh

      - name: Run Azure DevOps pipeline to update Databricks workspace with changes from prod
        run: bash .github/workflows/scripts/azure/update-workspace.sh
        env:
          PIPELINE_BRANCH: prod

      - name: Execute Azure DevOps pipeline to run tests on prod
        run: bash .github/workflows/scripts/azure/run-test.sh
        env:
          PIPELINE_BRANCH: prod