name: 'Push to dev'

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

concurrency:
  group: 'push-to-dev'
  cancel-in-progress: false

env:
  AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PAT }}
  AZDO_ORG_URL: ${{ secrets.AZDO_ORG_URL }}
  AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
  AZDO_GITHUB_SERVICE_CONNECTION: ${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION }}
  TARGET_ENV: DEV

permissions:
  contents: write

jobs:
  push-to-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get target and seed branch names and hashes
        id: get-branch-names
        run: bash .github/workflows/scripts/common/get-branch-names-and-hashes.sh

      - name: Check if source branch name is valid
        id: check-source-branch
        run: bash .github/workflows/scripts/common/check-source-branch-name.sh

      - name: Create a tag from the source branch name
        id: create-tag-from-branch-name
        run: bash .github/workflows/scripts/common/create-tag-from-branch-name.sh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure DevOps extension
        run: bash .github/workflows/scripts/azure/install-azure-devops-extension.sh

      - name: Run Azure DevOps pipeline to update Databricks workspace with changes from dev
        run: bash .github/workflows/scripts/azure/run-azdo-pipeline.sh
        env:
          PIPELINE_NAME: cs-databricks-update-workspace.yml
          PIPELINE_BRANCH: dev

      - name: Run Azure DevOps pipeline to execute tests on dev
        run: bash .github/workflows/scripts/azure/run-azdo-pipeline.sh
        env:
          PIPELINE_NAME: cs-databricks-run-tests.yml
          PIPELINE_BRANCH: dev
