name: 'Swap blue-green production environments'

on:
  workflow_dispatch:

env:
  AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZDO_PAT }}
  AZDO_ORG_URL: ${{ secrets.AZDO_ORG_URL }}
  AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
  AZDO_GITHUB_SERVICE_CONNECTION: ${{ secrets.AZDO_GITHUB_SERVICE_CONNECTION }}
  TARGET_ENV: PROD_BLUE

concurrency:
  group: 'swap-blue-green-prod-env'
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  ensure-pipeline-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure DevOps extension
        run: bash .github/workflows/scripts/azure/install-azure-devops-extension.sh

      - name: Run Azure DevOps pipeline check that both prod environments are healthy and ready for blue-green swap
        run: bash .github/workflows/scripts/azure/run-azdo-pipeline.sh
        env:
          PIPELINE_NAME: cs-check-if-prod-environments-are-active.yml
          PIPELINE_BRANCH: prod

      - name: Run Azure DevOps pipeline swap blue-green production environments
        run: bash .github/workflows/scripts/azure/run-azdo-pipeline.sh
        env:
          PIPELINE_NAME: cs-swap-blue-green-prod-env.yml
          PIPELINE_BRANCH: prod

      - name: Run Azure DevOps pipeline to execute smoke tests on main prod deployment
        run: bash .github/workflows/scripts/azure/run-azdo-pipeline.sh
        env:
          PIPELINE_NAME: cs-databricks-run-smoke-tests.yml
          PIPELINE_BRANCH: prod
